#!/usr/bin/env bash

mkdir "$1" && cd "$1" || exit

dotnet new console

cat <<EOF >Program.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace $1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine();
        }
    }
}
EOF

#nvim Program.cs
lvim Program.cs
